// <auto-generated />
using System;
using CourseWork2ApiServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseWork2ApiServer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseWork2ApiServer.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.DoctorsAppointment", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PatientTemperature")
                        .HasColumnType("float");

                    b.Property<bool>("Visited")
                        .HasColumnType("bit");

                    b.HasKey("PatientId", "DoctorId", "DateTime");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorsAppointments");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ExplorationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.OAuth", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("PatientId");

                    b.ToTable("OAuths");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PatientProcedure", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visited")
                        .HasColumnType("bit");

                    b.HasKey("PatientId", "ProcedureId", "DateTime");

                    b.HasIndex("ProcedureId");

                    b.ToTable("PatientProcedures");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PatientsDrug", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Remaining")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "DrugId", "DateOfManufacture");

                    b.HasIndex("DrugId");

                    b.ToTable("PatientsDrugs");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PrescribedMedication", b =>
                {
                    b.Property<int>("DoctorsAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DoctorsAppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorsAppointmentDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorsAppointmentPatientId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceptionTimeDuringTheDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceptionTimeInTheEvening")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceptionTimeInTheMorning")
                        .HasColumnType("bit");

                    b.Property<bool>("TakeAfterMeals")
                        .HasColumnType("bit");

                    b.Property<bool>("TakeBeforeMeals")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TakeMedicineBeforeTheDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TakeWithMeals")
                        .HasColumnType("bit");

                    b.HasKey("DoctorsAppointmentId", "DrugId");

                    b.HasIndex("DrugId");

                    b.HasIndex("DoctorsAppointmentPatientId", "DoctorsAppointmentDoctorId", "DoctorsAppointmentDateTime");

                    b.ToTable("PrescribedMedications");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.TakenMedication", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("ReceptionTimeDuringTheDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceptionTimeInTheEvening")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceptionTimeInTheMorning")
                        .HasColumnType("bit");

                    b.HasKey("PatientId", "DrugId", "DateTime");

                    b.HasIndex("DrugId");

                    b.ToTable("TakenMedications");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.WellBeingRecord", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("PatientId", "DateTime");

                    b.ToTable("WellBeingRecords");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.DoctorsAppointment", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("DoctorsAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.OAuth", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("Tokens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PatientProcedure", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("Procedures")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork2ApiServer.Models.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PatientsDrug", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("PatientsDrugs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.PrescribedMedication", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork2ApiServer.Models.DoctorsAppointment", "DoctorsAppointment")
                        .WithMany("PrescribedMedications")
                        .HasForeignKey("DoctorsAppointmentPatientId", "DoctorsAppointmentDoctorId", "DoctorsAppointmentDateTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorsAppointment");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.TakenMedication", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("TakenMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.WellBeingRecord", b =>
                {
                    b.HasOne("CourseWork2ApiServer.Models.Patient", "Patient")
                        .WithMany("WellBeingRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.DoctorsAppointment", b =>
                {
                    b.Navigation("PrescribedMedications");
                });

            modelBuilder.Entity("CourseWork2ApiServer.Models.Patient", b =>
                {
                    b.Navigation("DoctorsAppointments");

                    b.Navigation("PatientsDrugs");

                    b.Navigation("Procedures");

                    b.Navigation("TakenMedications");

                    b.Navigation("Tokens");

                    b.Navigation("WellBeingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
